name: Build .deb distribution package

on: push

jobs:

  build:

    name: Build .deb distribution package
    runs-on: ubuntu-18.04

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: debian.sh
