name: Build .deb distribution package

on: push

jobs:

  build:

    name: Build .deb distribution package
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Prep
      run: sudo apt install --yes build-essential cmake devscripts

    - name: Build
      run: ./debian.sh
